### ISSUE TITLE
Review project to see if we can send it to students

### ISSUE THREAD

**Issue by solojavier** [solojavier/social-networks-feed-service#2]
Hi,

I've completed the demo and improved the README. The view is now awesome thanks to Enrique..

Could you take a look at it and see if you consider there is anything else we should do before sending it?

It's incomplete on purpose, so we will see if a student dares to improve it or change something on it.

My idea is that we challenge them to do that and see what happens.

**Comment by andresf** [comment]
The parser has the facebook / twitter links set there. Won't the students need to modify those? If so, they should be moved to a config file as well.

**Comment by solojavier** [comment]
Not really... those need to be replaced by real parsed data....

**Comment by andresf** [comment]
So they DO have to modify them?

**Comment by solojavier** [comment]
No, they shouldn't modify those, they should delete them and add the implementation.

**Comment by andresf** [comment]
The README does not reflect this in that case.

**Comment by solojavier** [comment]
It's in the what's next section... I updated the message to be a little more descriptive

**Comment by andresf** [comment]
Ok, here's what I don't understand. These constants point to links to
RubyGDL, when they should be pointing at their own feeds, because the
access tokens are only valid for their own data, are they not? How will
they have the example up and running without modifying these?

Andrés Freyría Cedeño

2012/12/6 Javier Cervantes notifications@github.com

**Comment by solojavier** [comment]
Those links are there just to get a sense of how it should look like in the UI.

Those links are public and can be accessed by anyone.

The exercise is not currently working at 100%

**Comment by andresf** [comment]
So, if I'm following you, adding their facebook and twitter tokens isn't
actually necessary to see the feeds, only to post stuff (which they won't
be able to see reflected).

I don't see why not just make changing those part of the setup process.
It's going to be confusing and there is nothing in the documentation that
tells them this is how it's going to work.

2012/12/6 Javier Cervantes notifications@github.com

**Comment by solojavier** [comment]
Not quite, we are getting the message and the author from the social networks feed, those are the things missing for the client UI look nice.

**Comment by andresf** [comment]
I'm not quite sure I follow.

**Comment by solojavier** [comment]
:rabbit: ... Maybe we can see it like animals when you got a chance... just ping me :)

**Comment by solojavier** [comment]
Did we sent this or not?

**Comment by enrique-ramirez** [comment]
Send it already!
